#!/bin/sh
export VAULT_ADDR="http://localhost:8200"
VAULT_SUBNET=`docker exec vault_server ip route | awk '!/default/ {print $1}'`
SSH_HELPER_ADDR=`docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' vault_ssh_helper`

vault secrets list | grep -q "ssh/" \
    || vault secrets enable ssh
vault read ssh/roles/otp_role_ubuntu 1>/dev/null \
    || vault write ssh/roles/otp_role_ubuntu key_type=otp default_user=ubuntu cidr_list=$VAULT_SUBNET
vault write ssh/creds/otp_role_ubuntu ip=$SSH_HELPER_ADDR
ssh ubuntu@$SSH_HELPER_ADDR
